name: map_location_picker
description: Google Map location picker for flutter Based on google_maps_flutter.
version: 1.2.2
homepage: https://github.com/rvndsngwn/map_location_picker

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.4.0
  form_builder_extra_fields: ^10.0.0
  flutter_typeahead: ^4.6.2
  google_maps_webapi: ^0.0.22
  google_maps_flutter_web: ^0.5.3
  geolocator: ^9.0.2
  http: ^1.1.0
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
